# Generated by Django 4.0.4 on 2022-05-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
