# Generated by Django 4.0.4 on 2022-05-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvet', '0002_delete_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('pedido', models.TextField()),
            ],
        ),
    ]
