# Generated by Django 4.0.4 on 2022-05-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvet', '0003_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mascota',
            new_name='Mascotas',
        ),
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedidos',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
