# Generated by Django 4.0.4 on 2022-05-29 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvet', '0004_rename_mascota_mascotas_rename_pedido_pedidos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
